spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NutriMarket
    username: root
    password: 1234
  jpa:
    database-plataform: com.mysql.cj.jdbc.Driver
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
    mvc:
      throw-exception-if-no-handler-found: true
      async:
        request-timeout: 3600000
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      enabled: true
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
springdoc:
  swagger-ui:
    operationsSorter: method